// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Client.Templates.Files.Pages.Page
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Aryzac.IO.Modules.Client.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class PageTemplate : IntentTemplateBase<Aryzac.IO.Modules.Client.Api.PageModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<i18n lang=\"yaml\" src=\"./");
            
            #line 10 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(".i18n.yaml\" />\r\n\r\n<script setup lang=\"ts\">\r\nconst { t } = useI18n();\r\n\r\n");
            
            #line 15 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
 if (PageParameters.Count() > 0)
{

            
            #line default
            #line hidden
            this.Write("const route = useRoute();\r\n");
            
            #line 19 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 23 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

foreach (var pageParameter in PageParameters)
{

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 27 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageParameter.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = route.params.");
            
            #line 27 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageParameter.Name.ToPascalCase().ToCamelCase().ToLower()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 28 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

// add top and sidebar navigation checks here to ensure only a single use navigation setup instance
if (Model.BreadcrumbNavigation is not null)
{

            
            #line default
            #line hidden
            this.Write("const { setupSectionItem } = useNavigationSetup();\r\n");
            
            #line 38 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 42 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

if (Model.BreadcrumbNavigation is not null)
{

            
            #line default
            #line hidden
            this.Write("// Setup Breadcrumb\r\n");
            
            #line 46 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

  foreach (var item in Model.BreadcrumbNavigation.Items)
  {
    var navigationSettings = item.GetNavigationItemSettingss().FirstOrDefault();
    var page = item.TypeReference.Element.AsPageModel();

    var pageUrl = page.GetRoutePath();

    foreach (var mapping in item.InternalElement.Mappings) 
    {
      foreach (var mappingEnd in mapping.MappedEnds)
      {
        pageUrl = pageUrl.Replace($"[{mappingEnd.TargetElement.Name}]", $"${{{mappingEnd.SourceElement.Name.ToPascalCase().ToCamelCase()}}}");
      }
    }
      
      
            
            #line default
            #line hidden
            this.Write("setupSectionItem(\r\n  \"breadcrumb\", \r\n  t(\"breadcrumb.navigation.");
            
            #line 64 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\"), \r\n  ");
            
            #line 65 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
 if (navigationSettings?.Icon() != null) 
  { 
            
            #line default
            #line hidden
            this.Write("t(\"breadcrumb.navigation.");
            
            #line 66 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".icon\")");
            
            #line 66 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
 
  } 
  else 
  { 
            
            #line default
            #line hidden
            this.Write("null");
            
            #line 69 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

  } 
            
            #line default
            #line hidden
            this.Write(", \r\n  `");
            
            #line 71 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageUrl));
            
            #line default
            #line hidden
            this.Write("`,\r\n  false\r\n);\r\n");
            
            #line 74 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

  }
}

            
            #line default
            #line hidden
            this.Write("</script>\r\n\r\n<template>\r\n  <div>\r\n");
            
            #line 82 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
 if (Model.PageComponents != null)
{ 
	foreach (var pageComponent in Model.PageComponents)
	{

            
            #line default
            #line hidden
            this.Write("    <");
            
            #line 87 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPageComponentName(pageComponent)));
            
            #line default
            #line hidden
            this.Write(" \r\n\t");
            
            #line 88 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

      foreach (var mapping in pageComponent.InternalElement.Mappings)
      {
        foreach (var mappedEnd in mapping.MappedEnds)
        {
    
            
            #line default
            #line hidden
            this.Write("    :");
            
            #line 93 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.TargetElement.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write("=\"");
            
            #line 93 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.SourceElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 93 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

        }
      }
	
            
            #line default
            #line hidden
            this.Write("\t/>\r\n");
            
            #line 98 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Pages\Page\PageTemplate.tt"

	}
} 

            
            #line default
            #line hidden
            this.Write("  </div>\r\n</template>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
