// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Client.Templates.Files.Components.ComponentHtml
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.Html.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Aryzac.IO.Modules.Client.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ComponentHtmlTemplate : HtmlTemplateBase<Aryzac.IO.Modules.Client.Api.ComponentModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n\r\n");
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
 if (Model.View != null) {
  foreach (var component in Model.View.InternalElement.ChildElements) {
    if (component.IsHeadingModel()) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 16 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateHeading(component)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
 } else if (component.IsSectionModel()) {
      var section = component.AsSectionModel(); 
            
            #line default
            #line hidden
            this.Write("  <ui-editor-section\r\n    :title=\"t(\'");
            
            #line 20 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(component)));
            
            #line default
            #line hidden
            this.Write(".title\')\"\r\n    :description=\"t(\'");
            
            #line 21 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(component)));
            
            #line default
            #line hidden
            this.Write(".description\')\"\r\n  >\r\n");
            
            #line 23 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
 foreach (var control in section.InternalElement.ChildElements) {
    if (control.IsTextboxModel()) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 25 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateInputTextbox(control)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 26 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
  }
    if (control.IsTextAreaModel()) { 
            
            #line default
            #line hidden
            this.Write("     <ui-input-text-area \r\n       v-model=\"model.");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedTextAreaName(control.AsTextAreaModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 30 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(control)));
            
            #line default
            #line hidden
            this.Write(".label\')\" />\r\n");
            
            #line 31 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
  }
    if (control.IsCheckboxModel()) { 
            
            #line default
            #line hidden
            this.Write("     <ui-input-checkbox \r\n       v-model=\"model.");
            
            #line 34 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedCheckboxName(control.AsCheckboxModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 35 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(control)));
            
            #line default
            #line hidden
            this.Write(".label\')\" \r\n       :description=\"t(\'");
            
            #line 36 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(control)));
            
            #line default
            #line hidden
            this.Write(".description\')\" />\r\n");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
  }
    if (control.IsLabelModel()) { 
            
            #line default
            #line hidden
            this.Write("     <ui-input-label \r\n       v-model=\"");
            
            #line 40 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Label\" \r\n       :label=\"t(\'");
            
            #line 41 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(control)));
            
            #line default
            #line hidden
            this.Write(".label\')\" />\r\n");
            
            #line 42 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
  }
    if (control.IsRadioButtonModel()) { 
            
            #line default
            #line hidden
            this.Write("     <ui-input-radio-button \r\n       v-model=\"model.");
            
            #line 45 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedRadioButtonName(control.AsRadioButtonModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 46 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(control)));
            
            #line default
            #line hidden
            this.Write(".label\')\" />\r\n");
            
            #line 47 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
  }
    if (control.IsSelectModel()) {
      var select = control.AsSelectModel();
      var valueField = "";
      var labelField = "";
              
      foreach (var mapping in select.InternalElement.Mappings)
      {
          foreach (var mappingEnd in mapping.MappedEnds)
          {
              if (mappingEnd.TargetElement.SpecializationType == "Value")
              {
                  valueField = mappingEnd.SourceElement.Name;
              }
              if (mappingEnd.TargetElement.SpecializationType == "Select Label")
              {
                  labelField = mappingEnd.SourceElement.Name;
              }
          }
      }

            
            #line default
            #line hidden
            this.Write("     <ui-input-select \r\n       v-model=\"model.");
            
            #line 69 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedSelectName(control.AsSelectModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 70 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(control)));
            
            #line default
            #line hidden
            this.Write(".label\')\"\r\n       :options=\"");
            
            #line 71 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(select.InternalElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Options\"\r\n      />\r\n");
            
            #line 73 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
  }
    if (control.IsTableModel()) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 75 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateTable(control)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 76 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
  }
    if (control.IsActionsModel()) {
      var actions = control.AsActionsModel(); 
            
            #line default
            #line hidden
            this.Write("\r\n    <template #actions>\r\n");
            
            #line 81 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
 foreach (var action in actions.InternalElement.ChildElements) {
    var command = action.AsActionModel().Command; 
            
            #line default
            #line hidden
            this.Write("      <button\r\n        type=\"button\"\r\n        @click=\"");
            
            #line 85 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("()\"\r\n        class=\"rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text" +
                    "-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline" +
                    "-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600\"\r\n      >\r\n  " +
                    "      {{ t(\'");
            
            #line 88 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetI18nPath(action)));
            
            #line default
            #line hidden
            this.Write(".label\') }}\r\n      </button>\r\n    </template>\r\n    \r\n");
            
            #line 92 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"

          }
        }
      }

            
            #line default
            #line hidden
            this.Write("  </ui-editor-section>\r\n");
            
            #line 98 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
 } else if (component.IsTableModel()) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 99 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateTable(component)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 100 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\ComponentHtml\ComponentHtmlTemplate.tt"
 
    }
  }
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
