// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Client.Templates.Files.Composables.Controls.UseSelectOptions
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Aryzac.IO.Modules.Client.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class UseSelectOptionsTemplate : TypeScriptTemplateBase<Aryzac.IO.Modules.Client.Api.SelectModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DtoTypeImports));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nexport const use");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.InternalElement.GetFirstParentOfType(ComponentModel.SpecializationTypeId).Name.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Options = async (\r\n");
            
            #line 15 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
 if (GetComponent().Parameters != null) { 
            
            #line default
            #line hidden
            this.Write("  props: ");
            
            #line 16 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetComponent().Name));
            
            #line default
            #line hidden
            this.Write("Props, \r\n");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
 if (GetComponent().Model != null) { 
            
            #line default
            #line hidden
            this.Write("  model: ");
            
            #line 18 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetComponent().Name));
            
            #line default
            #line hidden
            this.Write("Model, \r\n");
            
            #line 19 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  t: ComposerTranslation\r\n) => {\r\n\r\n");
            
            #line 22 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommandAndQueryServiceProxyComposables));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 24 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Queries));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 26 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OptionsComputed));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nreturn {\r\n");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
 if (HasQueries()) { 
            
            #line default
            #line hidden
            this.Write("\tdata,\r\n\tpending,\r\n\terror,\r\n\texecute,\r\n\trefresh,\r\n\tstatus,\r\n");
            
            #line 36 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Composables\Controls\UseSelectOptions\UseSelectOptionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.InternalElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Options\r\n};\r\n\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
