name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE REQUEST]: "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a new feature!** We appreciate your input to help improve [Your Project Name]. Please fill out the details below to help us understand your vision for this feature.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Provide a brief summary of the feature or enhancement you're suggesting.
      placeholder: "A concise description of what you want to happen..."
    validations:
      required: true

  - type: textarea
    id: problem-solution
    attributes:
      label: Problem & Solution
      description: Describe the problem that this feature would solve or how it would enhance the project.
      placeholder: "The problem is... This feature solves the problem by..."
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Explain the benefits this feature would provide to the project or its users.
      placeholder: "This feature would improve..."
    validations:
      required: true

  - type: textarea
    id: potential-alternatives
    attributes:
      label: Potential Alternatives
      description: Have you considered any alternative solutions or features? If so, please describe them.
      placeholder: "Alternative solutions include..."
    validations:
      required: false

  - type: input
    id: user-story-link
    attributes:
      label: Link to Related User Story
      description: If this feature request is related to an existing user story, please provide the link here.
      placeholder: "https://github.com/yourproject/yourrepo/issues/"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the feature request here. This can help us better understand your proposal.
      placeholder: "Additional details..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **We look forward to your suggestions!** Your contributions are invaluable to making [Your Project Name] better for everyone. We'll review your feature request and get back to you with our feedback.
