// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Client.Templates.Files.Components.Component
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Aryzac.IO.Modules.Client.Api;
    using Intent.Modelers.Types.ServiceProxies.Api;
    using Intent.Modules.Metadata.WebApi.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ComponentTemplate : IntentTemplateBase<Aryzac.IO.Modules.Client.Api.ComponentModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<i18n lang=\"yaml\">\r\nen:\r\n");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
if (Model.View != null)
{
  foreach (var component in Model.View.InternalElement.ChildElements)
  {
    
    if (component.IsHeadingModel()) // Heading
    {
      Model.View.Heading.TryGetHeadingSettings(out var headingSettings);

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 24 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n    title: ");
            
            #line 25 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(headingSettings.Title() ?? Model.View.Heading.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 26 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
      foreach (var attribute in Model.View.Heading.Attributes)
      {

            
            #line default
            #line hidden
            this.Write("    attributes:\r\n      ");
            
            #line 31 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Label: ");
            
            #line 31 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name ?? "''"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

       }
    }
    else if (component.IsSectionModel()) // Section
    {
      var section = component.AsSectionModel();
      section.TryGetSectionSettings(out var sectionSettings);

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 40 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n    title: ");
            
            #line 41 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sectionSettings.Title() ?? component.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    description: ");
            
            #line 42 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sectionSettings.Description() ?? "''"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

      foreach (var control in section.InternalElement.ChildElements)
	  {

            
            #line default
            #line hidden
            
            #line 47 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsTextboxModel()) 
		{
          var textbox = control.AsTextboxModel();
          textbox.TryGetTextboxSettings(out var textboxSettings);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 53 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n      label: ");
            
            #line 54 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(textboxSettings.Label() ?? control.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 55 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 58 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsTextAreaModel()) 
		{
          var textarea = control.AsTextAreaModel();
          textarea.TryGetTextAreaSettings(out var textareaSettings);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 64 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n      label: ");
            
            #line 65 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(textareaSettings.Label() ?? control.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 66 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 69 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsCheckboxModel()) 
		{
          var checkbox = control.AsCheckboxModel();
          checkbox.TryGetCheckboxSettings(out var checkboxSettings);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 75 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n      label: ");
            
            #line 76 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(checkboxSettings.Label() ?? control.Name));
            
            #line default
            #line hidden
            this.Write("\r\n      description: ");
            
            #line 77 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(checkboxSettings.Description() ?? "''"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 78 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 81 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsLabelModel()) 
		{
          var label = control.AsLabelModel();
          label.TryGetLabelSettings(out var labelSettings);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 87 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n      label: ");
            
            #line 88 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(labelSettings.Label() ?? control.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 89 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 92 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsRadioButtonModel()) 
		{
          var radioButton = control.AsRadioButtonModel();
          radioButton.TryGetRadioButtonSettings(out var radioButtonSettings);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 98 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n      label: ");
            
            #line 99 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(radioButtonSettings.Label() ?? control.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 100 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 103 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsSelectModel()) 
		{
          var select = control.AsSelectModel();
          select.TryGetSelectSettings(out var selectSettings);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 109 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n      label: ");
            
            #line 110 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(selectSettings.Label() ?? control.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 111 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 114 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsTableModel()) 
		{
          var table = control.AsTableModel();

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 118 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n");
            
            #line 119 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

          foreach (var column in table.Columns)
	      { 

            
            #line default
            #line hidden
            this.Write("      ");
            
            #line 122 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 122 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 123 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
	      }
        }

            
            #line default
            #line hidden
            
            #line 127 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

      }

            
            #line default
            #line hidden
            
            #line 130 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
    }
	else if (component.IsTableModel()) // Table
    {

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 134 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":\r\n");
            
            #line 135 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

      foreach (var column in Model.View.Table.Columns)
	  { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 138 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 138 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 139 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
	  }
    }
  }
}

            
            #line default
            #line hidden
            this.Write("    \r\n</i18n>\r\n\r\n<script setup lang=\"ts\">\r\n");
            
            #line 149 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  if (Model.Query != null)
  {
    var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)Model.Query.Mapping.Element.AsOperationModel().Mapping.Element);
	
            
            #line default
            #line hidden
            this.Write("import type { ");
            
            #line 153 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(endpoint.ReturnType.Element.Name));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/dto/");
            
            #line 153 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)endpoint.ReturnType.Element).ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 153 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)endpoint.ReturnType.Element).MappedElement.Element.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".dto\';");
            
            #line 153 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 157 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
  if (Model.Command != null)
  {
    var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)Model.Command.Mapping.Element.AsOperationModel().Mapping.Element);
    if (endpoint.Inputs.FirstOrDefault(x => x.Source == HttpInputSource.FromBody) != null) 
    { 
        var bodyParam = endpoint.Inputs.First(x => x.Source == HttpInputSource.FromBody);

            
            #line default
            #line hidden
            this.Write("import type { ");
            
            #line 165 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(endpoint.InternalElement.Name));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/dto/");
            
            #line 165 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)bodyParam.TypeReference.Element).ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 165 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bodyParam.TypeReference.Element.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".dto\';\r\n");
            
            #line 166 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
    } 
  }

            
            #line default
            #line hidden
            this.Write("\r\nconst { t } = useI18n();\r\n\r\n");
            
            #line 173 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
  if (Model.Parameters != null)
  {
    
            
            #line default
            #line hidden
            this.Write("const props = defineProps<{\r\n");
            
            #line 177 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

    foreach (var parameter in Model.Parameters)
	{
	
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 180 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 180 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 181 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

	}
	
            
            #line default
            #line hidden
            this.Write("}>();\r\n\t");
            
            #line 184 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 188 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  foreach (var commandOrQuery in CommandsAndQueries)
  {

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 192 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commandOrQuery.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy = use");
            
            #line 192 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commandOrQuery.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Proxy();\r\n");
            
            #line 193 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 197 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  if (Queries.Any())
  {

            
            #line default
            #line hidden
            this.Write("// Queries");
            
            #line 201 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 205 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  foreach (var query in Queries)
  {

            
            #line default
            #line hidden
            this.Write("const { \r\n  data: ");
            
            #line 209 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 209 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Data, \r\n  pending: ");
            
            #line 210 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 210 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Pending, \r\n  error: ");
            
            #line 211 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 211 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Error \r\n} = await ");
            
            #line 212 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.AsOperationModel().ParentService.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy.");
            
            #line 212 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 212 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"


	var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)query.Mapping.Element.AsOperationModel().Mapping.Element);
		if (endpoint != null)
	{
	  foreach (var parameter in endpoint.Inputs)
	  {
	    
            
            #line default
            #line hidden
            this.Write("props.");
            
            #line 219 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 219 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        if (endpoint.Inputs.Last() != parameter)
		{
		
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 222 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		}
	  }
	}
	
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 227 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 231 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  if (Model.Model != null)
  {

            
            #line default
            #line hidden
            this.Write("// Model\r\ninterface ModelInterface {\r\n");
            
            #line 237 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
  
    foreach (var property in Model.Model.Properties)
    {

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 241 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 241 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 241 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(property.TypeReference)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 242 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("}\r\n\r\nconst model: ModelInterface = reactive({\r\n");
            
            #line 248 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
  
    foreach (var property in Model.Model.Properties)
    {

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 252 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": \"\",\r\n");
            
            #line 253 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("});\r\n\r\n");
            
            #line 258 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
   
    if (Model.Query != null)
    {

            
            #line default
            #line hidden
            this.Write("watchEffect(async () => {\r\n  if (");
            
            #line 263 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.InternalElement.ParentElement.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 263 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Data.value) {\r\n");
            
            #line 264 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
  
      foreach (var property in Model.Model.Properties)
      {

            
            #line default
            #line hidden
            this.Write("    model.");
            
            #line 268 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 268 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.InternalElement.ParentElement.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 268 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Data.value.");
            
            #line 268 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedPropertyName(property)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 269 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

      }
    }

            
            #line default
            #line hidden
            this.Write("  }\r\n})\r\n");
            
            #line 275 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 279 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  if (Commands.Any())
  {

            
            #line default
            #line hidden
            this.Write("// Commands");
            
            #line 283 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 287 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

  foreach (var command in Commands)
  {
	var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)command.Mapping.Element.AsOperationModel().Mapping.Element);

            
            #line default
            #line hidden
            this.Write("const save");
            
            #line 291 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" = async () => {\r\n\r\n");
            
            #line 293 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

	  foreach (var parameter in endpoint.Inputs.Where(m => m.TypeReference.Element.SpecializationType == "Command"))
	  {

            
            #line default
            #line hidden
            this.Write("  const command: ");
            
            #line 297 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" = {\r\n");
            
            #line 298 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
  
    foreach (var property in ((IElement)parameter.TypeReference.Element).ChildElements)
    {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 302 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": model.");
            
            #line 302 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedName(property)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 303 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  };\r\n");
            
            #line 307 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

	  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 311 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

	  foreach (var parameter in endpoint.Inputs.Where(m => m.TypeReference.Element.SpecializationType != "Command"))
	  {

            
            #line default
            #line hidden
            this.Write("  const ");
            
            #line 315 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 315 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" = props.id;\r\n");
            
            #line 316 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

	  }

            
            #line default
            #line hidden
            this.Write("\r\n\tconst ");
            
            #line 320 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await ");
            
            #line 320 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.AsOperationModel().ParentService.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy.");
            
            #line 320 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 320 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"


	if (endpoint != null)
	{
	  foreach (var parameter in endpoint.Inputs)
	  {
	    
            
            #line default
            #line hidden
            
            #line 326 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 326 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (endpoint.Inputs.Last() != parameter)
		{
		
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 329 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		}
	  }
	}
	
            
            #line default
            #line hidden
            this.Write(");\r\n};\r\n");
            
            #line 335 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 339 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
if (Model.View != null)
{
  foreach (var component in Model.View.InternalElement.ChildElements)
  {    

            
            #line default
            #line hidden
            this.Write("// ");
            
            #line 345 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name));
            
            #line default
            #line hidden
            this.Write(" Options\r\n\r\n");
            
            #line 347 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
   
    if (component.IsHeadingModel()) // Heading
    {

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 351 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Attributes = computed(() => [\r\n");
            
            #line 352 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
      foreach (var attribute in Model.View.Heading.Attributes)
      {
        attribute.TryGetAttributeSettings(out var attributeSettings);

            
            #line default
            #line hidden
            this.Write("  {\r\n\ticon: \'");
            
            #line 358 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributeSettings.Icon()));
            
            #line default
            #line hidden
            this.Write("\',\r\n\tlabel: t(\"");
            
            #line 359 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".attributes.");
            
            #line 359 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Label\"),\r\n  },\r\n");
            
            #line 361 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

       }

            
            #line default
            #line hidden
            this.Write("]\r\n);\r\n\r\nconst ");
            
            #line 366 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Actions = computed(() => [\r\n  {\r\n    label: \"Create Invoice\",\r\n    icon: \"heroico" +
                    "ns:plus\",\r\n    function: async () => {\r\n      await navigateTo(`/clients/${props" +
                    ".clientId}/invoices/create`);\r\n    },\r\n  },\r\n]);\r\n\r\n");
            
            #line 376 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

    }
	else if (component.IsSectionModel()) // Section
    {
      var section = component.AsSectionModel();

      foreach (var control in section.InternalElement.ChildElements)
	  {
		if (control.IsTableModel()) 
		{

            
            #line default
            #line hidden
            this.Write("// ");
            
            #line 387 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name));
            
            #line default
            #line hidden
            this.Write(" Options\r\n");
            
            #line 388 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

          var table = control.AsTableModel();

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 390 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Headers = [\r\n");
            
            #line 391 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
foreach (var column in table.Columns)
{

            
            #line default
            #line hidden
            this.Write("  {\r\n\tkey: \'");
            
            #line 396 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedColumnFieldName(column)));
            
            #line default
            #line hidden
            this.Write("\',\r\n\tlabel: t(\"");
            
            #line 397 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 397 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 397 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\"),\r\n  },\r\n");
            
            #line 399 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("];\r\n");
            
            #line 402 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }
      }

            
            #line default
            #line hidden
            
            #line 406 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

	}
	else if (component.IsTableModel()) // Table
    {

            
            #line default
            #line hidden
            this.Write("\r\n//");
            
            #line 412 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name));
            
            #line default
            #line hidden
            this.Write(" Options\r\nconst ");
            
            #line 413 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Headers = [\r\n");
            
            #line 414 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
foreach (var column in Model.View.Table.Columns)
{

            
            #line default
            #line hidden
            this.Write("  {\r\n\tkey: \'");
            
            #line 419 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\',\r\n\tlabel: t(\"");
            
            #line 420 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 420 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\"),\r\n  },\r\n");
            
            #line 422 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("];\r\n\r\n");
            
            #line 426 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
    }
  }
}

            
            #line default
            #line hidden
            this.Write("</script>\r\n\r\n<template>\r\n");
            
            #line 434 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
if (Model.View != null)
{
  foreach (var component in Model.View.InternalElement.ChildElements)
  {
    if (component.IsHeadingModel()) // Heading
    {

            
            #line default
            #line hidden
            this.Write("  <ui-heading-page\r\n    :title=\"t(\'");
            
            #line 443 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".title\')\"\r\n    :attributes=\"");
            
            #line 444 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Attributes\"\r\n    :actions=\"");
            
            #line 445 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Actions\"\r\n  />\r\n");
            
            #line 447 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

    }
    else if (component.IsSectionModel()) // Section
    {
      var section = component.AsSectionModel();

            
            #line default
            #line hidden
            this.Write("  <ui-editor-section\r\n    :title=\"t(\'");
            
            #line 454 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".title\')\"\r\n    :description=\"t(\'");
            
            #line 455 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".description\')\"\r\n  >\r\n");
            
            #line 457 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

      foreach (var control in section.InternalElement.ChildElements)
	  {

            
            #line default
            #line hidden
            
            #line 461 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsTextboxModel()) 
		{

            
            #line default
            #line hidden
            this.Write("     <ui-input-textbox \r\n       v-model=\"model.");
            
            #line 466 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedTextboxName(control.AsTextboxModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 467 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 467 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\')\" />\r\n");
            
            #line 468 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 471 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsTextAreaModel()) 
		{

            
            #line default
            #line hidden
            this.Write("     <ui-input-text-area \r\n       v-model=\"model.");
            
            #line 476 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedTextAreaName(control.AsTextAreaModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 477 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 477 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\')\" />\r\n");
            
            #line 478 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 481 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsCheckboxModel()) 
		{

            
            #line default
            #line hidden
            this.Write("     <ui-input-checkbox \r\n       v-model=\"model.");
            
            #line 486 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedCheckboxName(control.AsCheckboxModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 487 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 487 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\')\" \r\n       :description=\"t(\'");
            
            #line 488 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 488 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".description\')\" />\r\n");
            
            #line 489 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 492 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsLabelModel()) 
		{

            
            #line default
            #line hidden
            this.Write("     <ui-input-label \r\n       v-model=\"model.");
            
            #line 497 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedLabelName(control.AsLabelModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 498 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 498 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\')\" />\r\n");
            
            #line 499 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 502 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsRadioButtonModel()) 
		{

            
            #line default
            #line hidden
            this.Write("     <ui-input-radio-button \r\n       v-model=\"model.");
            
            #line 507 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedRadioButtonName(control.AsRadioButtonModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 508 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 508 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\')\" />\r\n");
            
            #line 509 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 512 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsSelectModel()) 
		{

            
            #line default
            #line hidden
            this.Write("     <ui-input-select \r\n       v-model=\"model.");
            
            #line 517 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedSelectName(control.AsSelectModel())));
            
            #line default
            #line hidden
            this.Write("\" \r\n       :label=\"t(\'");
            
            #line 518 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 518 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\')\" />\r\n");
            
            #line 519 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 522 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsTableModel()) 
		{
          var table = control.AsTableModel();

            
            #line default
            #line hidden
            this.Write("  <ui-view-table\r\n    :items=\"");
            
            #line 528 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 528 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Data\"\r\n    :headers=\"");
            
            #line 529 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Headers\"\r\n    key=\"id\"\r\n  />\r\n");
            
            #line 532 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 535 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

		if (control.IsComponentCommandModel()) 
		{
          var command = control.AsComponentCommandModel();

            
            #line default
            #line hidden
            this.Write("\r\n    <template #actions>\r\n      <button\r\n        type=\"button\"\r\n        @click=\"" +
                    "save");
            
            #line 544 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(@"()""
        class=""rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600""
      >
        Save
      </button>
    </template>
    
");
            
            #line 551 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 554 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

      }

            
            #line default
            #line hidden
            this.Write("  </ui-editor-section>\r\n");
            
            #line 558 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"

	}
	else if (component.IsTableModel()) // Table
    {
          var table = component.AsTableModel();

            
            #line default
            #line hidden
            this.Write("  <ui-view-table\r\n    :items=\"");
            
            #line 565 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 565 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Data\"\r\n    :headers=\"");
            
            #line 566 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Headers\"\r\n    key=\"id\"\r\n  />\r\n");
            
            #line 569 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ComponentTemplate.tt"
 
    }
  }
}

            
            #line default
            #line hidden
            this.Write("</template>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
