// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Modules.Client.Templates.Files.Components.Component
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Aryzac.IO.Modules.Client.Api;
    using Intent.Modelers.Types.ServiceProxies.Api;
    using Intent.Modules.Metadata.WebApi.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ScriptTemplate : IntentTemplateBase<Aryzac.IO.Modules.Client.Api.ComponentModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<script setup lang=\"ts\">\r\n");
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
  foreach (var query in Queries)
  {
    var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)query.Mapping.Element.AsOperationModel().Mapping.Element);
	
            
            #line default
            #line hidden
            this.Write("import type { ");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(endpoint.ReturnType.Element.Name));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/dto/");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)endpoint.ReturnType.Element).ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)endpoint.ReturnType.Element).MappedElement.Element.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".dto\';\r\n");
            
            #line 18 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 22 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
  foreach (var command in Commands)
  {
    var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)command.Mapping.Element.AsOperationModel().Mapping.Element);
    if (endpoint.Inputs.FirstOrDefault(x => x.Source == HttpInputSource.FromBody) != null) 
    { 
        var bodyParam = endpoint.Inputs.First(x => x.Source == HttpInputSource.FromBody);

            
            #line default
            #line hidden
            this.Write("import type { ");
            
            #line 30 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(endpoint.InternalElement.Name));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/dto/");
            
            #line 30 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)bodyParam.TypeReference.Element).ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 30 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bodyParam.TypeReference.Element.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".dto\';\r\n");
            
            #line 31 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
    } 
  }

            
            #line default
            #line hidden
            this.Write("\r\nconst { t } = useI18n();\r\n\r\n");
            
            #line 38 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
  if (Model.Parameters != null)
  {
    
            
            #line default
            #line hidden
            this.Write("const props = defineProps<{\r\n");
            
            #line 42 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    foreach (var parameter in Model.Parameters)
	{
	
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 45 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 45 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 46 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	}
	
            
            #line default
            #line hidden
            this.Write("}>();\r\n\t");
            
            #line 49 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 53 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  foreach (var commandOrQuery in CommandsAndQueries)
  {

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 57 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commandOrQuery.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy = use");
            
            #line 57 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commandOrQuery.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Proxy();\r\n");
            
            #line 58 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 62 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  if (Queries.Any())
  {

            
            #line default
            #line hidden
            this.Write("// Queries");
            
            #line 66 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 70 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  foreach (var query in Queries)
  {

            
            #line default
            #line hidden
            this.Write("const { \r\n  data: ");
            
            #line 74 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 74 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Data, \r\n  pending: ");
            
            #line 75 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 75 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Pending, \r\n  error: ");
            
            #line 76 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 76 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Error , \r\n  execute: ");
            
            #line 77 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 77 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Execute, \r\n  refresh: ");
            
            #line 78 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 78 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Refresh, \r\n  status: ");
            
            #line 79 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 79 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Status \r\n} = await ");
            
            #line 80 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.AsOperationModel().ParentService.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy.");
            
            #line 80 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 80 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"


	foreach (var mapping in query.InternalElement.Mappings)
    {
        foreach (var mappedEnd in mapping.MappedEnds)
        {
	      
            
            #line default
            #line hidden
            this.Write("props.");
            
            #line 86 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.SourceElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 86 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

          if (mapping.MappedEnds.Last() != mappedEnd)
		  {
		  
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 89 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

		  }
	    }
	}
	
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 94 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 98 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  if (Model.Model != null)
  {

            
            #line default
            #line hidden
            this.Write("// Model\r\ninterface ModelInterface {\r\n");
            
            #line 104 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
  
    foreach (var property in Model.Model.Properties)
    {

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 108 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 108 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 108 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(property.TypeReference)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 109 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("}\r\n\r\nconst model: ModelInterface = reactive({\r\n");
            
            #line 115 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
  
    foreach (var property in Model.Model.Properties)
    {

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 119 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": \"\",\r\n");
            
            #line 120 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("});\r\n\r\n");
            
            #line 125 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
   
    if (Model.Query != null)
    {

            
            #line default
            #line hidden
            this.Write("watchEffect(async () => {\r\n  if (");
            
            #line 130 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 130 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Data.value) {\r\n");
            
            #line 131 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
  
      foreach (var property in Model.Model.Properties)
      {

            
            #line default
            #line hidden
            this.Write("    model.");
            
            #line 135 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 135 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 135 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Data.value.");
            
            #line 135 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedPropertyName(property)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 136 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      }
    }

            
            #line default
            #line hidden
            this.Write("  }\r\n});\r\n");
            
            #line 142 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 146 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  if (Commands.Any())
  {

            
            #line default
            #line hidden
            this.Write("// Commands");
            
            #line 150 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 154 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  foreach (var command in Commands)
  {
    var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)command.Mapping.Element.AsOperationModel().Mapping.Element);
    var commandParameter = command.InternalElement.ChildElements.FirstOrDefault(m => m.SpecializationType == "Parameter" && m.Name == "command");
	

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 160 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = async (");
            
            #line 160 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	foreach (var mapping in command.InternalElement.Mappings.Where(m => m.TypeId == "0ca6626b-5dc2-42f4-a0dd-2ff7aabd684b"))
    {
        foreach (var mappedEnd in mapping.MappedEnds)
        {
            var source = "props";

            switch (mappedEnd.SourceElement.SpecializationType)
            {
                case "DTO-Field":

            
            #line default
            #line hidden
            
            #line 170 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.TargetElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 170 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(mappedEnd.TargetElement.TypeReference)));
            
            #line default
            #line hidden
            
            #line 170 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

                if (mapping.MappedEnds.Last() != mappedEnd)
		        {
		          
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 173 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

		        }
                    break;
            }
	    }
	}

            
            #line default
            #line hidden
            this.Write(") => {\r\n\r\n");
            
            #line 181 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	  foreach (var parameter in endpoint.Inputs.Where(m => m.TypeReference.Element.SpecializationType == "Command"))
	  {

            
            #line default
            #line hidden
            this.Write("  const command: ");
            
            #line 185 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" = {\r\n");
            
            #line 186 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
  
    foreach (var property in ((IElement)commandParameter.TypeReference.Element).ChildElements)
    {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 190 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": model.");
            
            #line 190 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappedName(property, command)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 191 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  };\r\n");
            
            #line 195 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 199 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	foreach (var mapping in command.InternalElement.Mappings.Where(m => m.TypeId == "0ca6626b-5dc2-42f4-a0dd-2ff7aabd684b"))
    {
        foreach (var mappedEnd in mapping.MappedEnds.Where(m => m.SourceElement.SpecializationType != "DTO-Field"))
        {
            var source = "props";

            switch (mappedEnd.SourceElement.SpecializationType)
            {
                case "Component Parameter":
                    source = "props";
                    break;
                case "Component Model Field":
                    source = "model";
                    break;
            }

	      
            
            #line default
            #line hidden
            this.Write("  const ");
            
            #line 216 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.TargetElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 216 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 216 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.SourceElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n          ");
            
            #line 217 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	    }
	}

            
            #line default
            #line hidden
            this.Write("\r\n\tconst ");
            
            #line 222 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await ");
            
            #line 222 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.AsOperationModel().ParentService.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy.");
            
            #line 222 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 222 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"


	if (endpoint != null)
	{
	  foreach (var parameter in endpoint.Inputs)
	  {
	    
            
            #line default
            #line hidden
            
            #line 228 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 228 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

		if (endpoint.Inputs.Last() != parameter)
		{
		
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 231 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

		}
	  }
	}
	
            
            #line default
            #line hidden
            this.Write(");\r\n};\r\n");
            
            #line 237 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 241 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
if (Model.View != null)
{
  foreach (var component in Model.View.InternalElement.ChildElements)
  {    

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 248 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
   
    if (component.IsHeadingModel()) // Heading
    {

            
            #line default
            #line hidden
            this.Write("// ");
            
            #line 252 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name));
            
            #line default
            #line hidden
            this.Write(" Options\r\n");
            
            #line 253 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      var heading = component.AsHeadingModel();
            
      var mappedColumn = heading.InternalElement.ParentElement.Mappings.First().MappedEnds.FirstOrDefault(m => m.MappingTypeId == "d9cb10dc-82ed-4378-8385-e9cc8be76c40" && m.TargetElement.SpecializationType == "Heading");

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 258 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(heading.InternalElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Title = computed(() => {\r\n");
            
            #line 259 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      var mappedExpression = mappedColumn.MappingExpression;
      foreach (var source in mappedColumn.Sources)
      {
        mappedExpression = mappedExpression.Replace($"{{{source.ExpressionIdentifier}}}", $"${{{source.Element.Name.ToPascalCase().ToCamelCase()}}}");

            
            #line default
            #line hidden
            this.Write("  const ");
            
            #line 265 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = model.");
            
            #line 265 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" || \'\';\r\n");
            
            #line 266 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      }

            
            #line default
            #line hidden
            this.Write("  const mappedExpression = `");
            
            #line 269 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedExpression));
            
            #line default
            #line hidden
            this.Write("`;\r\n  return mappedExpression;\r\n});\r\nconst ");
            
            #line 272 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Attributes = computed(() => [\r\n");
            
            #line 273 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
      foreach (var attribute in Model.View.Heading.Attributes)
      {
        var mappedAttributeColumn = attribute.InternalElement.ParentElement.ParentElement.Mappings.First().MappedEnds.FirstOrDefault(m => 
          m.MappingTypeId == "d9cb10dc-82ed-4378-8385-e9cc8be76c40" && 
          m.TargetElement.SpecializationType == "Heading Attribute" &&
          m.TargetElement.Id == attribute.Id);

        if (mappedAttributeColumn is not null)
        {
          var mappedAttributeExpression = mappedAttributeColumn.MappingExpression;
       
          foreach (var source in mappedAttributeColumn.Sources)
          {
            mappedAttributeExpression = mappedAttributeExpression.Replace($"{{{source.ExpressionIdentifier}}}", $"${{model.{source.Element.Name.ToPascalCase().ToCamelCase()}}}");
          }

            
            #line default
            #line hidden
            this.Write("  {\r\n\ticon: t(\"");
            
            #line 291 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".attributes.");
            
            #line 291 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".icon\"),\r\n\tlabel: `");
            
            #line 292 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedAttributeExpression));
            
            #line default
            #line hidden
            this.Write("`,\r\n  },\r\n");
            
            #line 294 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("  {\r\n\ticon: t(\"");
            
            #line 300 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".attributes.");
            
            #line 300 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".icon\"),\r\n\tlabel: t(\"");
            
            #line 301 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".attributes.");
            
            #line 301 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\"),\r\n  },\r\n");
            
            #line 303 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

       }
      }

            
            #line default
            #line hidden
            this.Write("]\r\n);\r\n\r\nconst ");
            
            #line 309 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Actions = [\r\n");
            
            #line 310 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
    if (Model.View.Heading.Actions is not null)
    {
foreach (var action in Model.View.Heading.Actions.Actions)
{

            
            #line default
            #line hidden
            this.Write("  {\r\n    label: t(\"");
            
            #line 317 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Heading.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".actions.");
            
            #line 317 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\"),\r\n");
            
            #line 318 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    if (action.Navigation is not null)
    {
      var page = action.Navigation.TypeReference.Element.AsPageModel();
      var pageUrl = page.GetRoutePath();

      foreach (var mapping in action.Navigation.InternalElement.Mappings) // .Where(m => m.TypeId == "90548e07-a8af-41a1-b608-d07b35d98fa3"))
      {
        foreach (var mappingEnd in mapping.MappedEnds)
        {
          pageUrl = pageUrl.Replace($"[{mappingEnd.TargetElement.Name}]", $"${{props.{mappingEnd.SourceElement.Name.ToPascalCase().ToCamelCase()}}}");
        }
      }

            
            #line default
            #line hidden
            this.Write("    action: async () => {\r\n      const localeRoute = useLocaleRoute();\r\n      awa" +
                    "it navigateTo(localeRoute(`");
            
            #line 334 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageUrl));
            
            #line default
            #line hidden
            this.Write("`));\r\n    },\r\n");
            
            #line 336 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }
    else if (action.Command is not null)
    {

            
            #line default
            #line hidden
            this.Write("    action: async (item: ");
            
            #line 341 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)action.Command.InternalElement.Mappings.First().MappedEnds.First().SourceElement).ParentElement.Name));
            
            #line default
            #line hidden
            this.Write(") => {\r\n      await ");
            
            #line 342 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Command.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 342 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	foreach (var mapping in action.Command.InternalElement.Mappings.Where(m => m.TypeId == "0ca6626b-5dc2-42f4-a0dd-2ff7aabd684b"))
    {
        foreach (var mappedEnd in mapping.MappedEnds)
        {
            var source = "props";

            switch (mappedEnd.SourceElement.SpecializationType)
            {
                case "DTO-Field":

            
            #line default
            #line hidden
            this.Write("item.");
            
            #line 352 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.TargetElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 352 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

                if (mapping.MappedEnds.Last() != mappedEnd)
		        {
		          
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 355 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

		        }
                    break;
            }
	    }
	}

            
            #line default
            #line hidden
            this.Write(");\r\n    },\r\n");
            
            #line 363 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  },\r\n");
            
            #line 367 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

}
}

            
            #line default
            #line hidden
            this.Write("];\r\n\r\n");
            
            #line 372 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }
	else if (component.IsSectionModel()) // Section
    {
      var section = component.AsSectionModel();

      foreach (var control in section.InternalElement.ChildElements)
	  {
		if (control.IsTableModel()) 
		{

            
            #line default
            #line hidden
            this.Write("// ");
            
            #line 383 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name));
            
            #line default
            #line hidden
            this.Write(" Options\r\n");
            
            #line 384 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

          var table = control.AsTableModel();

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 386 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Headers = [\r\n");
            
            #line 387 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
foreach (var column in table.Columns)
{
  var mappedColumn = table.InternalElement.Mappings.First().MappedEnds.FirstOrDefault(m => m.TargetElement.Id == column.Id);

            
            #line default
            #line hidden
            this.Write("  {\r\n\tkey: \'");
            
            #line 393 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\',\r\n\tlabel: t(\"");
            
            #line 394 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 394 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\"),\r\n    data: (item: ");
            
            #line 395 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)mappedColumn.Sources.First().Element).ParentElement.Name));
            
            #line default
            #line hidden
            this.Write(") => {\r\n");
            
            #line 396 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    var mappedExpression = mappedColumn.MappingExpression;
    foreach (var source in mappedColumn.Sources)
    {
        mappedExpression = mappedExpression.Replace($"{{{source.ExpressionIdentifier}}}", $"${{{source.Element.Name.ToPascalCase().ToCamelCase()}}}");

            
            #line default
            #line hidden
            this.Write("      const ");
            
            #line 402 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = item.");
            
            #line 402 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" || \'\';\r\n");
            
            #line 403 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("      const mappedExpression = `");
            
            #line 406 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedExpression));
            
            #line default
            #line hidden
            this.Write("`;\r\n      return mappedExpression;\r\n    }\r\n  },\r\n");
            
            #line 410 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("];\r\n\r\nconst ");
            
            #line 414 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Actions = [\r\n");
            
            #line 415 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
if (table.Actions is not null)
{
foreach (var action in table.Actions.Actions)
{
    action.TryGetActionSettings(out var actionSettings);

            
            #line default
            #line hidden
            this.Write("  {\r\n    label: t(\"");
            
            #line 423 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".actions.");
            
            #line 423 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\"),\r\n");
            
            #line 424 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      if (actionSettings.Icon() is not null)
      {

            
            #line default
            #line hidden
            this.Write("    icon: t(\"");
            
            #line 428 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".actions.");
            
            #line 428 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".icon\"),\r\n");
            
            #line 429 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      }

            
            #line default
            #line hidden
            
            #line 432 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    if (action.Navigation is not null)
    {
      var page = action.Navigation.TypeReference.Element.AsPageModel();
      var pageUrl = page.GetRoutePath();

      foreach (var mapping in action.Navigation.InternalElement.Mappings) // .Where(m => m.TypeId == "90548e07-a8af-41a1-b608-d07b35d98fa3"))
      {
        foreach (var mappingEnd in mapping.MappedEnds)
        {
          pageUrl = pageUrl.Replace($"[{mappingEnd.TargetElement.Name}]", $"${{item.{mappingEnd.SourceElement.Name.ToPascalCase().ToCamelCase()}}}");
        }
      }

            
            #line default
            #line hidden
            this.Write("    action: async (item: ");
            
            #line 446 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)action.Navigation.InternalElement.Mappings.First().MappedEnds.First().SourceElement).ParentElement.Name));
            
            #line default
            #line hidden
            this.Write(") => {\r\n      const localeRoute = useLocaleRoute();\r\n      await navigateTo(local" +
                    "eRoute(`");
            
            #line 448 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageUrl));
            
            #line default
            #line hidden
            this.Write("`));\r\n    },\r\n");
            
            #line 450 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }
    else if (action.Command is not null)
    {

            
            #line default
            #line hidden
            this.Write("    action: async (item: ");
            
            #line 455 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)action.Command.InternalElement.Mappings.First().MappedEnds.First().SourceElement).ParentElement.Name));
            
            #line default
            #line hidden
            this.Write(") => {\r\n      await ");
            
            #line 456 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Command.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 456 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	foreach (var mapping in action.Command.InternalElement.Mappings.Where(m => m.TypeId == "0ca6626b-5dc2-42f4-a0dd-2ff7aabd684b"))
    {
        foreach (var mappedEnd in mapping.MappedEnds)
        {
            var source = "props";

            switch (mappedEnd.SourceElement.SpecializationType)
            {
                case "DTO-Field":

            
            #line default
            #line hidden
            this.Write("item.");
            
            #line 466 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.TargetElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 466 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

                if (mapping.MappedEnds.Last() != mappedEnd)
		        {
		          
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 469 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

		        }
                    break;
            }
	    }
	}

            
            #line default
            #line hidden
            this.Write(");\r\n    },\r\n");
            
            #line 477 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  },\r\n");
            
            #line 481 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

}
}

            
            #line default
            #line hidden
            this.Write("];\r\n");
            
            #line 485 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 488 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

        else if (control.IsSelectModel())
        {

            
            #line default
            #line hidden
            this.Write("// ");
            
            #line 492 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name));
            
            #line default
            #line hidden
            this.Write(" Options\r\n");
            
            #line 493 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

          var select = control.AsSelectModel();
          var valueField = "";
          var labelField = "";
            
          var mappedColumn = select.InternalElement.Mappings.First().MappedEnds.FirstOrDefault(m => m.MappingTypeId == "74330c09-3675-4796-b7c9-8f5132b9c59b");

          foreach (var mapping in select.InternalElement.Mappings)
          {
            foreach (var mappingEnd in mapping.MappedEnds)
            {
                if (mappingEnd.TargetElement.SpecializationType == "Value")
                {
                    valueField = mappingEnd.SourceElement.Name;
                }
            }
          }

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 511 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(select.InternalElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Options = computed(() => {\r\n  const options: { value: string; label: string }[] =" +
                    " [];\r\n  if (");
            
            #line 513 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(select.InternalElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 513 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(select.Query.Mapping.Element.Name));
            
            #line default
            #line hidden
            this.Write("Data.value) {\r\n    ");
            
            #line 514 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(select.InternalElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 514 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(select.Query.Mapping.Element.Name));
            
            #line default
            #line hidden
            this.Write("Data.value.forEach((item: ");
            
            #line 514 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(select.Query.Mapping.Element.TypeReference.Element.Name));
            
            #line default
            #line hidden
            this.Write(") => {\r\n");
            
            #line 515 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    var mappedExpression = mappedColumn.MappingExpression;
    foreach (var source in mappedColumn.Sources)
    {
        mappedExpression = mappedExpression.Replace($"{{{source.ExpressionIdentifier}}}", $"${{{source.Element.Name.ToPascalCase().ToCamelCase()}}}");

            
            #line default
            #line hidden
            this.Write("      const ");
            
            #line 521 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = item.");
            
            #line 521 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" || \'\';\r\n");
            
            #line 522 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("      const mappedExpression = `");
            
            #line 525 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedExpression));
            
            #line default
            #line hidden
            this.Write("`;\r\n\r\n      options.push({\r\n        value: item.");
            
            #line 528 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(valueField.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(",\r\n        label: mappedExpression,\r\n      });\r\n    });\r\n  }\r\n  return options;\r\n" +
                    "});\r\n");
            
            #line 535 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 538 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

        else if (control.IsLabelModel())
        {

            
            #line default
            #line hidden
            this.Write("// ");
            
            #line 542 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(control.Name));
            
            #line default
            #line hidden
            this.Write(" Options\r\n");
            
            #line 543 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

          var label = control.AsLabelModel();
          var labelField = "";
            
          var mappedColumn = label.InternalElement.ParentElement.ParentElement.Mappings.First().MappedEnds.FirstOrDefault(m => m.MappingTypeId == "d9cb10dc-82ed-4378-8385-e9cc8be76c40" && m.TargetElement.SpecializationType == "Label" && m.TargetElement.Id == control.Id);

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 549 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(label.InternalElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Label = computed(() => {\r\n");
            
            #line 550 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

          var mappedExpression = mappedColumn.MappingExpression;
          foreach (var source in mappedColumn.Sources)
          {
            mappedExpression = mappedExpression.Replace($"{{{source.ExpressionIdentifier}}}", $"${{{source.Element.Name.ToPascalCase().ToCamelCase()}}}");

            
            #line default
            #line hidden
            this.Write("  const ");
            
            #line 556 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = model.");
            
            #line 556 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" || \'\';\r\n");
            
            #line 557 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

          }

            
            #line default
            #line hidden
            this.Write("  const mappedExpression = `");
            
            #line 560 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedExpression));
            
            #line default
            #line hidden
            this.Write("`;\r\n  return mappedExpression;\r\n});\r\n");
            
            #line 563 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 566 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      }

            
            #line default
            #line hidden
            
            #line 569 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	}
	else if (component.IsTableModel()) // Table
    {

            
            #line default
            #line hidden
            this.Write("\r\n// ");
            
            #line 575 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(component.Name));
            
            #line default
            #line hidden
            this.Write(" Options\r\nconst ");
            
            #line 576 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Headers = [\r\n");
            
            #line 577 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
foreach (var column in Model.View.Table.Columns)
{
  var mappedColumn = Model.View.Table.InternalElement.Mappings.First().MappedEnds.FirstOrDefault(m => m.TargetElement.Id == column.Id);

            
            #line default
            #line hidden
            this.Write("  {\r\n\tkey: \'");
            
            #line 583 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\',\r\n\tlabel: t(\"");
            
            #line 584 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 584 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\"),\r\n    data: (item: ");
            
            #line 585 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)mappedColumn.Sources.First().Element).ParentElement.Name));
            
            #line default
            #line hidden
            this.Write(") => {\r\n");
            
            #line 586 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    var mappedExpression = mappedColumn.MappingExpression;
    foreach (var source in mappedColumn.Sources)
    {
        mappedExpression = mappedExpression.Replace($"{{{source.ExpressionIdentifier}}}", $"${{{source.Element.Name.ToPascalCase().ToCamelCase()}}}");

            
            #line default
            #line hidden
            this.Write("      const ");
            
            #line 592 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = item.");
            
            #line 592 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(source.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" || \'\';\r\n");
            
            #line 593 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("      const mappedExpression = `");
            
            #line 596 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedExpression));
            
            #line default
            #line hidden
            this.Write("`;\r\n      return mappedExpression;\r\n    }\r\n  },\r\n");
            
            #line 600 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("];\r\n\r\nconst ");
            
            #line 604 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Actions = [\r\n");
            
            #line 605 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
if (Model.View.Table.Actions is not null)
{
foreach (var action in Model.View.Table.Actions.Actions)
{
    action.TryGetActionSettings(out var actionSettings);

            
            #line default
            #line hidden
            this.Write("  {\r\n    label: t(\"");
            
            #line 613 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".actions.");
            
            #line 613 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".label\"),\r\n");
            
            #line 614 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      if (actionSettings.Icon() is not null)
      {

            
            #line default
            #line hidden
            this.Write("    icon: t(\"");
            
            #line 618 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.View.Table.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".actions.");
            
            #line 618 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".icon\"),\r\n");
            
            #line 619 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

      }

            
            #line default
            #line hidden
            
            #line 622 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    if (action.Navigation is not null)
    {
      var page = action.Navigation.TypeReference.Element.AsPageModel();
      var pageUrl = page.GetRoutePath();

      foreach (var mapping in action.Navigation.InternalElement.Mappings) // .Where(m => m.TypeId == "90548e07-a8af-41a1-b608-d07b35d98fa3"))
      {
        foreach (var mappingEnd in mapping.MappedEnds)
        {
          pageUrl = pageUrl.Replace($"[{mappingEnd.TargetElement.Name}]", $"${{item.{mappingEnd.SourceElement.Name.ToPascalCase().ToCamelCase()}}}");
        }
      }

            
            #line default
            #line hidden
            this.Write("    action: async (item: ");
            
            #line 636 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)action.Navigation.InternalElement.Mappings.First().MappedEnds.First().SourceElement).ParentElement.Name));
            
            #line default
            #line hidden
            this.Write(") => {\r\n      const localeRoute = useLocaleRoute();\r\n      await navigateTo(local" +
                    "eRoute(`");
            
            #line 638 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageUrl));
            
            #line default
            #line hidden
            this.Write("`));\r\n    },\r\n");
            
            #line 640 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }
    else if (action.Command is not null)
    {

            
            #line default
            #line hidden
            this.Write("    action: async (item: ");
            
            #line 645 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)action.Command.InternalElement.Mappings.First().MappedEnds.First().SourceElement).ParentElement.Name));
            
            #line default
            #line hidden
            this.Write(") => {\r\n      await ");
            
            #line 646 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Command.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 646 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

	foreach (var mapping in action.Command.InternalElement.Mappings.Where(m => m.TypeId == "0ca6626b-5dc2-42f4-a0dd-2ff7aabd684b"))
    {
        foreach (var mappedEnd in mapping.MappedEnds)
        {
            var source = "props";

            switch (mappedEnd.SourceElement.SpecializationType)
            {
                case "DTO-Field":

            
            #line default
            #line hidden
            this.Write("item.");
            
            #line 656 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.TargetElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 656 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

                if (mapping.MappedEnds.Last() != mappedEnd)
		        {
		          
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 659 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

		        }
                    break;
            }
	    }
	}

            
            #line default
            #line hidden
            this.Write(");\r\n    },\r\n");
            
            #line 667 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  },\r\n");
            
            #line 671 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("];\r\n\r\n");
            
            #line 675 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
 
    }
  }
}
}

            
            #line default
            #line hidden
            this.Write("\r\nonMounted(() => {\r\n");
            
            #line 683 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  foreach (var query in Queries)
  {

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 687 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 687 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.Mapping.Element.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Execute();\r\n");
            
            #line 688 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Modules.Client\Templates\Files\Components\Component\ScriptTemplate.tt"

  }

            
            #line default
            #line hidden
            this.Write("});\r\n</script>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
