// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.IO.Client.Nuxt.Templates.Files.Components.Component
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Aryzac.IO.Modules.Client.Api;
    using Intent.Modelers.Types.ServiceProxies.Api;
    using Intent.Modules.Metadata.WebApi.Models;
    using Aryzac.IO.Client.Nuxt;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\ComponentTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ComponentTemplate : IntentTemplateBase<Aryzac.IO.Modules.Client.Api.ComponentModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n<i18n lang=\"yaml\" src=\"@/locales/components");
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./i18n/i18n.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.GetPath().ToKebabCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./i18n/i18n.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".i18n.yaml\" />");
            this.Write("\r\n");
            this.Write("\r\n<script setup lang=\"ts\">\r\n\r\n");
            this.Write("\r\n");
            
            #line 12 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 if (Model.Parameters != null) { 
            
            #line default
            #line hidden
            this.Write("import type { ");
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Props } from \'~/structs/components/");
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".props\';\r\n");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 } 
            
            #line default
            #line hidden
            
            #line 15 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 if (Model.Model != null) { 
            
            #line default
            #line hidden
            this.Write("import type { ");
            
            #line 16 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Model } from \'~/structs/components/");
            
            #line 16 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.InternalElement.ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 16 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".model\';\r\n");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 19 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 
  foreach (var query in Queries)
  {
    var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)query.Mapping.Element.AsOperationModel().Mapping.Element);
	
            
            #line default
            #line hidden
            this.Write("import type { ");
            
            #line 23 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(endpoint.ReturnType.Element.Name));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/dto/");
            
            #line 23 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)endpoint.ReturnType.Element).ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 23 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)endpoint.ReturnType.Element).MappedElement.Element.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".dto\';\r\n");
            
            #line 24 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"

  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 28 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 
  foreach (var command in Commands)
  {
    var endpoint = HttpEndpointModelFactory.GetEndpoint((IElement)command.Mapping.Element.AsOperationModel().Mapping.Element);
    if (endpoint.Inputs.FirstOrDefault(x => x.Source == HttpInputSource.FromBody) != null) 
    { 
        var bodyParam = endpoint.Inputs.First(x => x.Source == HttpInputSource.FromBody);

            
            #line default
            #line hidden
            this.Write("import type { ");
            
            #line 36 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(endpoint.InternalElement.Name));
            
            #line default
            #line hidden
            this.Write(" } from \'~/structs/dto/");
            
            #line 36 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((IElement)bodyParam.TypeReference.Element).ParentElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 36 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bodyParam.TypeReference.Element.Name.ToKebabCase()));
            
            #line default
            #line hidden
            this.Write(".dto\';\r\n");
            
            #line 37 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 
    } 
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 42 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 foreach (var composable in GetAllComposables()) { 
    var importPath = $"~/composables/components/{composable.GetComposablePath()}/use{composable.GetFirstParentOfType(ComponentModel.SpecializationTypeId).Name.ToPascalCase()}{composable.Name.ToPascalCase()}Options";

            
            #line default
            #line hidden
            this.Write("import { use");
            
            #line 45 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composable.GetFirstParentOfType(ComponentModel.SpecializationTypeId).Name.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 45 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composable.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Options } from \'");
            
            #line 45 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(importPath));
            
            #line default
            #line hidden
            this.Write("\'\r\n");
            
            #line 46 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./TypeImport.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nconst { t } = useI18n();\r\n\r\n");
            this.Write("\r\n");
            
            #line 12 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./Properties.tt"
 if (Model.Parameters != null) { 
            
            #line default
            #line hidden
            this.Write("const props = defineProps<");
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./Properties.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Props>();\r\n");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\.\Script\./Properties.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 20 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

  foreach (var commandOrQuery in CommandsAndQueries)
  {

            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 24 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commandOrQuery.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy = use");
            
            #line 24 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commandOrQuery.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Proxy();\r\n");
            
            #line 25 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
   
  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 29 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
   
  if (Model.Query is not null && Model.Query.Mapping is not null)
  {

            
            #line default
            #line hidden
            this.Write("const query = await ");
            
            #line 33 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.Mapping.Element.AsOperationModel().ParentService.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Proxy.");
            
            #line 33 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.Mapping.Element.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 33 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"


    foreach (var mapping in Model.Query.InternalElement.Mappings)
    {
      foreach (var mappedEnd in mapping.MappedEnds)
      {
	    
            
            #line default
            #line hidden
            this.Write("props.");
            
            #line 39 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappedEnd.SourceElement.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 39 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

        if (mapping.MappedEnds.Last() != mappedEnd)
		{
		
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 42 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

		}
	  }
	}
	
            
            #line default
            #line hidden
            this.Write(");");
            
            #line 46 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

  } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 49 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

  if (Model.Model != null)
  {

            
            #line default
            #line hidden
            this.Write("const model = reactive<");
            
            #line 53 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Model>({} as ");
            
            #line 53 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Model);\r\n\r\n");
            
            #line 55 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
   
    if (Model.Query != null)
    {

            
            #line default
            #line hidden
            this.Write("watchEffect(async () => {\r\n  if (query.data.value) {\r\n    Object.assign(model, qu" +
                    "ery.data.value);\r\n");
            
            #line 62 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

    }

            
            #line default
            #line hidden
            this.Write("  }\r\n});\r\n");
            
            #line 67 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

  }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 71 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
 foreach (var composable in GetAllComposables()) { 
            
            #line default
            #line hidden
            this.Write("const ");
            
            #line 72 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composable.Name.ToPascalCase().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Options = await use");
            
            #line 72 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composable.GetFirstParentOfType(ComponentModel.SpecializationTypeId).Name.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 72 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composable.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Options(");
            
            #line 72 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetComposableMethodParameters(composable)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 73 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nonMounted(() => {\r\n");
            
            #line 76 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

  if (Model.Query is not null && Model.Query.Mapping is not null)
  {

            
            #line default
            #line hidden
            this.Write("  query.execute();\r\n");
            
            #line 81 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Script/Script.tt"

  }

            
            #line default
            #line hidden
            this.Write("});\r\n</script>\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            
            #line 12 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Template/Template.tt"
 Model.TryGetComponentSettings(out var componentSettings); 
            
            #line default
            #line hidden
            
            #line 13 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Template/Template.tt"
 if (componentSettings is not null && componentSettings.SeparateTemplate()) { 
            
            #line default
            #line hidden
            this.Write("<template src=\"./");
            
            #line 14 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Template/Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(".template.html\" />\r\n");
            
            #line 15 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Template/Template.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("<template>\r\n");
            
            #line 17 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Template/Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HtmlTemplate));
            
            #line default
            #line hidden
            this.Write("\r\n</template>\r\n");
            
            #line 19 "D:\src\aryzac-io\aryzac.io.Modules\src\Aryzac.IO.Client.Nuxt\Templates\Files\Components\Component\./Template/Template.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
